#%RAML 1.0 Library
usage: RAML resource types

uses: 
  types: types.raml

resourceTypes: 
  collection:
    description: Collection of <<resourcePathName>>.
  # Tratamento dos responses para os métodos GET    
    get?:
      description: Get a list of <<resourcePathName>>.
      responses:
        200:
          body:
            application/json:
              type: <<typeCollection>>
              example: <<exampleCollection>>
        400: &400-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-400.json
        401: &401-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-401.json
        403: &403-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-403.json
        404: &404-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-404.json
        500: &500-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-500.json
    # Tratamento dos responses para os métodos POST  
    post?:
      description: Create a new <<resourcePathName|!singularize>> record.
      body: &body-request-item
        application/json:
              type: <<postRequest>>
              example: <<examplePostRequestCollection>>
      responses:
        200: &body-response-item
          body:
            application/json:
              type: <<PostResponse>>
              example: <<examplePostResponseCollection>>
              
        400: &400-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-400.json
        401: &401-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-401.json
        403: &403-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-403.json
        404: &404-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-404.json
        500: &500-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-500.json
    # Tratamento dos responses para os métodos PUT  
    put?:
      description: Create a new <<resourcePathName|!singularize>> record.
      
      responses:
        200: &body-response-item
          body:
            application/json:
              type: <<PutResponse>>
              example: <<examplePutResponseCollection>>
              
        400: &400-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-400.json
        401: &401-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-401.json
        403: &403-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-403.json
        404: &404-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-404.json
        500: &500-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-500.json  
              
    # Tratamento dos responses para os métodos DELETE              
    delete?:
      description: Create a new <<resourcePathName|!singularize>> record.
      
      responses:
        200: &body-response-item
          body:
            application/json:
              type: <<DeleteResponse>>
              example: <<exampleDeleteResponseCollection>>
              
        400: &400-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-400.json
        401: &401-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-401.json
        403: &403-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-403.json
        404: &404-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-404.json
        500: &500-error
          body:
            application/json:
              type: types.ErrorMessageDefinition
              example: !include ../examples/resources-error/error-500.json       
    